# Generated by Django 5.0.6 on 2025-05-26 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddingApp_RSVP', '0004_remove_rsvp_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPEG/PNG Only', upload_to='gallery_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(help_text='Select the person who is uploading this photo', on_delete=django.db.models.deletion.CASCADE, to='weddingApp_RSVP.attendee')),
            ],
        ),
    ]
