# Generated by Django 5.0.6 on 2025-05-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='attendee',
        ),
        migrations.AddField(
            model_name='photo',
            name='message',
            field=models.CharField(blank=True, help_text='A short message (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default=2, help_text='Your name (required)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/'),
        ),
    ]
