# Generated by Django 5.0.6 on 2024-06-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('family_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('response', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='weddingApp_RSVP.rsvp')),
            ],
        ),
    ]
