# Generated by Django 5.0.6 on 2024-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp_RSVP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='after_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='ceremony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='zoom',
            field=models.BooleanField(default=False),
        ),
    ]
