# Generated by Django 5.0.6 on 2024-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp_RSVP', '0002_rsvp_after_party_rsvp_ceremony_rsvp_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
