# Generated by Django 5.0.6 on 2024-06-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weddingApp_RSVP', '0003_rsvp_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='zoom',
        ),
    ]
